R/write-plumber.R, tests/testthat/_snaps/write-plumber.md, tests/testthat/test-write-plumber.R
With `rapidoc` being suggested, it is not guaranteed that it is available.
=> Sanity check for the `docs` package to be installed

NEWS.md, R/handlers.R, man/vetiver_type_convert.Rd, tests/testthat/test-type-convert.R
=> Escalate warnings to errors in `vetiver_type_convert()`

R/open-api-spec.R, R/pr-predict.R, man/vetiver_pr_predict.Rd, tests/testthat/test-caret.R, tests/testthat/test-pr-predict.R, tests/testthat/test-tidymodels.R, tests/testthat/test-xgboost.R
Closes #66 
``` r
library(tidymodels)
data(bivariate)
biv_rec <-
recipe(Class ~ ., data = bivariate_train) %>%
step_BoxCox(all_predictors())%>%
step_normalize(all_predictors())
svm_spec <-
svm_linear(mode = "classification") %>%
set_engine("LiblineaR")
svm_fit <- workflow() %>%
add_recipe(biv_rec) %>%
add_model(svm_spec) %>%
fit(bivariate_train)
#> 
#> Attaching package: 'vetiver'
#> The following object is masked from 'package:tune':
#> 
#>     load_pkgs
v <- vetiver_model(svm_fit, "biv_svm")
v
#> 
#> ── biv_svm ─ <butchered_workflow> model for deployment 
#> A LiblineaR classification modeling workflow using 2 features
library(plumber)
pr() %>%
vetiver_pr_predict(v, type = "class", debug = TRUE)
#> # Plumber router with 2 endpoints, 4 filters, and 0 sub-routers.
#> # …
```
=> Add health check endpoint

.github/workflows/R-CMD-check.yaml
This is hopefully like rstudio/pins#562
=> Check for things in other dirs

DESCRIPTION, R/handlers.R, man/vetiver_type_convert.Rd, tests/testthat/_snaps/predict.md, tests/testthat/_snaps/type-convert.md, tests/testthat/helper-plumber.R, tests/testthat/test-api.R, tests/testthat/test-caret.R, tests/testthat/test-choose-version.R, tests/testthat/test-glm.R, tests/testthat/test-mlr3.R, tests/testthat/test-pin-read-write.R, tests/testthat/test-predict.R, tests/testthat/test-ranger.R, tests/testthat/test-tidymodels.R, tests/testthat/test-type-convert.R, tests/testthat/test-write-docker.R, tests/testthat/test-write-plumber.R, tests/testthat/test-xgboost.R
The goal is to set up the vetiver API in some kind of background process and then call it from the main process for tests.
=> Add tests for calling API

tests/testthat/test-monitor.R
Closes #95 
Thank you so much for this report @mfansler! 🙌 
For your project, do you need this change on CRAN, or is merged into main here good enough? I probably won't do another CRAN release for a few weeks.
=> Update monitoring test for more skipping

NEWS.md, R/write-docker.R, man/vetiver_write_docker.Rd, tests/testthat/_snaps/write-docker.md, tests/testthat/test-write-docker.R
Closes #101 
Related to rstudio/vetiver-python#58
=> Add `EXPOSE` for Docker Desktop users

README.Rmd, README.md
Related to rstudio/vetiver-python#59
=> Add link to Python docs in README

NEWS.md, R/open-api-spec.R, tests/testthat/_snaps/write-docker.md
Closes #110 
Thank you so much for the nudge @tyluRp!
I believe this works both for models that are versioned:
And unversioned:
=> Add version to OpenAPI spec

DESCRIPTION, NEWS.md, R/write-docker.R, tests/testthat/_snaps/write-docker.md, tests/testthat/test-write-docker.R
* Fixed bug: #142 
* Added apt-get clean to reduce docker container size
* Updated tests
* Bumped version & news
=> Fixes #142

inst/mtcars_keras.R
avoid implicit promotion of `y` from a 1d array to 2d array
=> minor edit to keras example

DESCRIPTION, R/attach-pkgs.R, R/rsconnect.R, R/write-plumber.R, README.Rmd, README.md, cran-comments.md, man/attach_pkgs.Rd, man/vetiver_create_rsconnect_bundle.Rd, man/vetiver_dashboard.Rd, man/vetiver_deploy_rsconnect.Rd, man/vetiver_pin_metrics.Rd, man/vetiver_pin_write.Rd, man/vetiver_prepare_docker.Rd, man/vetiver_write_plumber.Rd, tests/testthat/test-monitor.R, vignettes/vetiver.Rmd
=> Release candidate v0.2.0

R/monitor.R, man/vetiver_compute_metrics.Rd, man/vetiver_pin_metrics.Rd, man/vetiver_plot_metrics.Rd
=> Fix `vetiver_pin_metrics()` arg docs

DESCRIPTION, R/pin-read-write.R, _pkgdown.yml, tests/testthat/_snaps/monitor.md
This PR updates vetiver to the new pins on CRAN.
=> Update to new pins

tests/testthat/test-monitor.R
=> Turn vdiffr test for plot back on

R/open-api-spec.R, tests/testthat/test-api.R, tests/testthat/test-write-docker.R
=> Hide Connect redirect

NEWS.md, R/write-docker.R, tests/testthat/test-write-docker.R
=> Fix where `vetiver_write_docker()` puts renv lockfile

R/keras.R, R/write-docker.R, tests/testthat/_snaps/keras.md, tests/testthat/test-keras.R
=> Add Docker support for keras

R/rsconnect.R, man/vetiver_deploy_rsconnect.Rd
=> Add details on authenticated calls to `/predict` for Connect

R/sagemaker.R, man/vetiver_deploy_sagemaker.Rd
Addresses #246 and the other times folks have had trouble working locally with SageMaker
=> Add some advice for SageMaker users working locally

.github/workflows/R-CMD-check.yaml, DESCRIPTION, R/write-docker.R, tests/testthat/_snaps/monitor/default-metrics-plot.svg, tests/testthat/test-keras.R, tests/testthat/test-luz.R
We've got some new failures in CI to address.
=> Some boring maintenance, to get CI passing

R/rsconnect.R, man/vetiver_deploy_rsconnect.Rd
=> Fix docs for RStudio ➡️ Posit

R/rsconnect.R, R/sagemaker.R, man/vetiver_create_rsconnect_bundle.Rd, man/vetiver_deploy_rsconnect.Rd, man/vetiver_deploy_sagemaker.Rd, man/vetiver_sm_build.Rd
Closes #278 with links to Posit Connect and SageMaker
=> Add links to platforms/products

.github/workflows/R-CMD-check.yaml
To fix the vdiffr related failure in #283
=> Bump vdiffr version
