R/pr-predict.R, R/vetiver-model.R, man/vetiver_create_ptype.Rd, man/vetiver_model.Rd, man/vetiver_pr_predict.Rd, tests/testthat/_snaps/choose-version.md, tests/testthat/test-pr-predict.R
This PR separates the act of saving a data prototype (`save_ptype` when creating a model) with using that prototype for checking at prediction time (`check_ptype`). The default behavior stays the same but this lets a user add a prototype for visual documentation but not use it for the vetiver checking (just use whatever the model does natively with wrongly typed data).
This change is at least partly to maintain parity with the Python implementation for vetiver.
@isabelizimm can you take a look at this and see if this aligns with what we spoke about?
=> Add `check_ptype` arg

NEWS.md, R/write-docker.R, man/vetiver_write_docker.Rd, tests/testthat/_snaps/write-docker.md
Closes #99 
@ggpinto Thank you so much for the feedback! 🙌  Would you like to take a look at this and see if it would fit your use case?
``` r
library(pins)
b <- board_temp(versioned = TRUE)
cars_lm <- lm(mpg ~ ., data = mtcars)
v <- vetiver_model(cars_lm, "cars_linear")
vetiver_pin_write(b, v)
#> Creating new version '20220606T221019Z-9ca24'
#> Writing to pin 'cars_linear'
#> 
#> Create a Model Card for your published model
#> • Model Cards provide a framework for transparent, responsible reporting
#> • Use the vetiver `.Rmd` template as a place to start
vetiver_write_plumber(b, "cars_linear")
vetiver_write_docker(v)
#> * Lockfile written to 'vetiver_renv.lock'.
cat(readr::read_lines("Dockerfile"), sep = "\n")
#> # Generated by the vetiver package; edit with care
#> 
#> …
```
=> Make a new arg `lockfile` for Dockerfile generation

NEWS.md, R/monitor.R, man/vetiver_compute_metrics.Rd, tests/testthat/test-monitor.R
Closes #102 
When we show an example dashboard, we will now use `overwrite = TRUE` when using this function. The default `overwrite = FALSE` is the better choice for interactive use.
=> Switch default for `overwrite` to `FALSE`

DESCRIPTION, R/dashboard.R, R/ptype.R, tests/testthat/_snaps/api.md, tests/testthat/_snaps/choose-version.md, tests/testthat/_snaps/create-ptype.md, tests/testthat/_snaps/dashboard.md, tests/testthat/_snaps/predict.md, tests/testthat/_snaps/ranger.md, tests/testthat/test-dashboard.R
Related to #98
This PR corrects how the call is used in the error message for the `vetiver_dashboard()` function.
=> Use call in error message for dashboard

tests/testthat/test-dashboard.R
Dashboard tests fail if `rmarkdown` package not installed. The `rmarkdown::available_templates()` method was [added in v2.12](https://github.com/rstudio/rmarkdown/releases/tag/v2.12). This adds a skip condition.
Nothing urgent.
=> check rmarkdown in tests

NEWS.md, R/pin-read-write.R, man/vetiver_pin_write.Rd
This PR addresses #118 by passing the dots from `vetiver_pin_write()` through to `pins::pin_write()`. This let you do something like:
```r
b <- pins::board_rsconnect()
cars_lm <- lm(mpg ~ ., data = mtcars)
v <- vetiver_model(cars_lm, "cars_linear")
vetiver_pin_write(b, v, access_type = "all")
```
=> Pass the dots to `pin_write()`

inst/rmarkdown/templates/vetiver_dashboard/skeleton/skeleton.Rmd
This PR adds "This model was published X days ago" to the dashboard, as well as removing the in-hindsight weird "source code" link to our docs site.
=> Add age of model to dashboard

DESCRIPTION, NEWS.md, R/endpoint.R, man/vetiver_endpoint.Rd
Closes #120 
I spent some time looking around for options to validate that a string is a URL and it doesn't seem like I have many options other [than a regular expression](https://rex.r-lib.org/articles/url_parsing.html) (or making a HTTP call). I think I will wait on this and see if it's a common problem people run into.
=> Remove any trailing slash in `vetiver_endpoint()`

NEWS.md, R/write-docker.R, tests/testthat/test-write-docker.R
Closes #146 by making a special case for stats and _not_ including it when making the renv lockfile
=> Make the stats pkg a special case

DESCRIPTION, R/write-docker.R
Closes #150 
I couldn't reproduce any problems with the existing strategy because RSPM knows how to find system requirements for packages including dependencies, but this is probably a better strategy in case any weird edge cases or problems come up.
=> Better strategy for identifying system reqs

NEWS.md, R/lm.R, R/ptype.R, R/vetiver-package.R, tests/testthat/_snaps/glm.md, tests/testthat/test-create-ptype.R, tests/testthat/test-glm.R
Closes #158 
This uses the approach that hardhat took in tidymodels/hardhat#175 to identify when a model has any interactions:
``` r
cars_lm <- lm(mpg ~ cyl*gear + disp, data = mtcars)
vetiver_ptype(cars_lm)
#> # A tibble: 0 × 3
#> # … with 3 variables: cyl <dbl>, gear <dbl>, disp <dbl>
```
<sup>Created on 2022-11-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
=> Fix how `vetiver_ptype()` works for models with interactions

NEWS.md, R/endpoint.R, tests/testthat/test-predict.R
Closes #167 
As show in the above issue ⤴️ we had a problem with how all-`NA` columns were handled in `predict.vetiver_endpoint`. With this change, `NA` values are stored as strings in the JSON passed over in the request body. The test shows how we can now predict with all-`NA` columns, and the example with xgboost now works.
=> Change `NA` handling in JSON conversion

.github/workflows/R-CMD-check.yaml
Let's try to fix the new problems installing ranger on R 4.0.x.
Gabor thinks this could be fixed in ranger itself or by putting `CXXFLAGS += -std=gnu++14` in Makevars, but let's try just ignoring it.
=> Ignore ranger before R 4.1.0

NEWS.md, R/pin-read-write.R, tests/testthat/test-pin-read-write.R
Closes #189 
No incorrect message now:
``` r
library(tidymodels)
library(pins)
#> 
#> Attaching package: 'vetiver'
#> The following object is masked from 'package:tune':
#> 
#>     load_pkgs
data(bivariate)
ranger_fit <- 
workflow(Class ~ A + B, rand_forest(mode = "classification")) %>%
fit(bivariate_train)
v <- vetiver_model(ranger_fit, "biv-rf")
b <- board_temp()
b %>% vetiver_pin_write(v, check_renv = TRUE)
#> Creating new version '20230407T172359Z-f060b'
#> Writing to pin 'biv-rf'
#> 
#> Create a Model Card for your published model
#> • Model Cards provide a framework for transparent, responsible reporting
#> • Use the vetiver `.Rmd` template as a place to start
out <- b %>% vetiver_pin_read("biv-rf", check_renv = TRUE)
```
<sup>Created on 2023-04-07 with [reprex …
=> Fix `check_renv` behavior

R/sagemaker.R, man/vetiver_deploy_sagemaker.Rd, man/vetiver_sm_build.Rd
You can't actually use any board at all when deploying to SageMaker.
=> Document S3-specific pins board for SageMaker

R/write-docker.R
Currently there is no check to see if the `plumber_file` argument leads to a real plumber file. It is possible to create a Dockerfile with a non-existent plumber file at present. See reprex below. 
This PR adds a check to verify that the plumber file does indeed exist. 
``` r
cars_lm <- lm(mpg ~ ., data = mtcars)
v <- vetiver_model(cars_lm, "cars_linear")
dir.create("inst/vetiver", recursive = TRUE)
vetiver_write_docker(v, path = "inst/vetiver")
#> The version of R recorded in the lockfile will be updated:
#> - R             [* -> 4.3.0]
#> 
#> * Lockfile written to 'vetiver_renv.lock'.
list.files("inst/vetiver")
#> [1] "Dockerfile"
list.files()
#> [1] "inst" "vetiver_renv.lock"
```
=> Verify that `plumber_file` exists before creating Dockerfile

R/sagemaker.R, man/vetiver_sm_build.Rd
Addresses the typo mentioned in https://github.com/rstudio/vetiver-r/issues/215
=> Fixed typo in the docs for the `role` arg in `vetiver_sm_build()`

inst/netflix_tidymodels.R, inst/rmarkdown/templates/vetiver_model_card/skeleton/skeleton.Rmd, vignettes/vetiver.Rmd
Addresses https://github.com/rstudio/vetiver-r/issues/188 and related to https://github.com/rstudio/pins-r/issues/678
=> Changing `board_rsconnect()` to `board_connect()` as the former was deprecated in pins 1.1.0.

DESCRIPTION, R/api.R, R/open-api-spec.R, inst/chicago_rpart.R, man/vetiver_api.Rd, tests/testthat/helper.R, tests/testthat/test-api.R, tests/testthat/test-predict.R
=> Add new `/prototype` endpoint

R/rsconnect.R, tests/testthat/test-rsconnect.R
Recent releases of renv + rsconnect have caused some problems for this Connect test, since we can't make a manifest that is actually deployable with a source installation of vetiver. Let's see if this will fix it. 🤞
=> Mock `rsconnect::writeManifest()` in test

R/rsconnect.R, man/vetiver_deploy_rsconnect.Rd, tests/testthat/setup.R
For Posit Connect, it will be helpful to give folks a little more hinting around the difference between `appName` and `appTitle`. I do think it's the _title_ that we want to set up with some nice automated treatment (rather than the name) but folks have gotten confused.
More on these arguments here:
https://rstudio.github.io/rsconnect/reference/deployApp.html
=> Add `appName` example to dots

.github/workflows/R-CMD-check.yaml, NEWS.md, R/write-plumber.R
Closes #239 
With this change, I now can correctly generate code for a `board_url()`.
``` r
library(pins)
b <- board_url(c(
chicago_model = 'https://colorado.posit.co/rsc/chicago-rstats-model-pin/'
))
deparse(board_deparse(b))
#> [1] "board_url(c(chicago_model = \"https://colorado.posit.co/rsc/chicago-rstats-model-pin/\"))"
```
<sup>Created on 2023-09-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
=> Use base R `deparse()` when writing `plumber.R`

NEWS.md, R/write-plumber.R
Addresses these user-reported issues:
- #253 
- #256 
The change in #241 turned out to actually break generating the plumber files for more complex boards like S3 and similar. 😩 
I need to think about testing across different board types in vetiver. The pins package is tested very extensively across all the backends but vetiver does not, and here it is the code that _vetiver_ ran that was the problem. I could probably get away with mocking `vetiver_pin_read()` in such tests to avoid needing to call S3 like pins CI does.
=> Go back to `rlang::expr_deparse()` except for `board_url()`

DESCRIPTION, R/mlr3.R
We want to remove`$task_prototype` in mlr3 and use  `$data_prototype` instead. Both will be available for some time.
=> refactor: change task_prototype to data_prototype

DESCRIPTION, R/recipe.R, tests/testthat/test-recipe.R
Closes #286 
~~The recipes tests now skip on older versions but I didn't bump in `DESCRIPTION`. Maybe I should just bump though, actually.~~
I did decide to bump the version for recipes in `DESCRIPTION`; I think that's better than trying to support both moving forward.
=> When a recipe has a `ptype`, use it to set up the vetiver model

tests/testthat/test-mlr3.R
Adds a skip when `xgboost` is not installed. Otherwise, test will fail with:
```r
── Error ('test-mlr3.R:34:5'): learners from mlr3learners can be pinned ────────
<packageNotFoundError/error/condition>
Error: The following packages could not be loaded: xgboost
Backtrace:
▆
1. └─learner$train(task) at test-mlr3.R:34:5
2.   └─mlr3:::.__Learner__train(...)
3.     └─mlr3:::learner_train(...)
4.       └─mlr3misc::require_namespaces(learner$packages)
```
=> Add xgboost check
